/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_B0_06 (number 105), UART1_TXD/J17[6] */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_TXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_TXD_SIGNAL                                       TX   /*!< Signal name */

/* GPIO_AD_B0_07 (number 101), UART1_RXD/J17[4] */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_RXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_RXD_SIGNAL                                       RX   /*!< Signal name */

/* GPIO_AD_B0_12 (number 96), ENET_RXER/U11[20]/J19[4] */
/* Routed pin properties */
#define BOARD_INITPINS_ADC1_PERIPHERAL                                      ADC1   /*!< Peripheral name */
#define BOARD_INITPINS_ADC1_SIGNAL                                            IN   /*!< Signal name */
#define BOARD_INITPINS_ADC1_CHANNEL                                           0U   /*!< Signal channel */

/* GPIO_EMC_33 (number 123), SEMC_D9/U14[44] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D9_PERIPHERAL                                 LPSPI4   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D9_SIGNAL                                       PCS0   /*!< Signal name */

/* GPIO_EMC_34 (number 122), SEMC_D10/U14[45] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D10_PERIPHERAL                                LPSPI4   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D10_SIGNAL                                       SDO   /*!< Signal name */

/* GPIO_EMC_35 (number 121), SEMC_D11/U14[47] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D11_PERIPHERAL                                LPSPI4   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D11_SIGNAL                                       SDI   /*!< Signal name */

/* GPIO_EMC_32 (number 124), SEMC_D8/U14[42] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D8_PERIPHERAL                                 LPSPI4   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D8_SIGNAL                                        SCK   /*!< Signal name */

/* GPIO_EMC_36 (number 120), SEMC_D12/U14[48] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D12_PERIPHERAL                                LPSPI4   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D12_SIGNAL                                      PCS1   /*!< Signal name */

/* GPIO_EMC_05 (number 13), SEMC_D5/U14[10] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D5_PERIPHERAL                                  GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D5_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D5_CHANNEL                                        5U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D5_GPIO                                        GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D5_GPIO_PIN                                       5U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D5_GPIO_PIN_MASK                          (1U << 5U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_SEMC_D5_PORT                                        GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_SEMC_D5_PIN                                            5U   /*!< PORT pin number */
#define BOARD_INITPINS_SEMC_D5_PIN_MASK                               (1U << 5U)   /*!< PORT pin mask */

/* GPIO_EMC_09 (number 8), SEMC_WE/U14[16] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_WE_PERIPHERAL                                   TMR1   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_WE_SIGNAL                                TIMER_INPUT   /*!< Signal name */
#define BOARD_INITPINS_SEMC_WE_CHANNEL                                        1U   /*!< Signal channel */

/* GPIO_EMC_39 (number 117), SEMC_D15/U14[53] */
/* Routed pin properties */
#define BOARD_INITPINS_SEMC_D15_PERIPHERAL                                 GPIO3   /*!< Peripheral name */
#define BOARD_INITPINS_SEMC_D15_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SEMC_D15_CHANNEL                                       7U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SEMC_D15_GPIO                                       GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SEMC_D15_GPIO_PIN                                      7U   /*!< GPIO pin number */
#define BOARD_INITPINS_SEMC_D15_GPIO_PIN_MASK                         (1U << 7U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_SEMC_D15_PORT                                       GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_SEMC_D15_PIN                                           7U   /*!< PORT pin number */
#define BOARD_INITPINS_SEMC_D15_PIN_MASK                              (1U << 7U)   /*!< PORT pin mask */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
